version: "3.1"
services:
  sparklis:
    image: medirad-docker-virtual.artifact.b-com.com/sparklis:${SPARKLIS_TAG}
    container_name: sparklis

  fhir:
    container_name: fhir
    image: medirad-docker-virtual.artifact.b-com.com/hapi-fhir:${FHIR_TAG}
    environment:
      JAVA_OPTIONS: -Xms10g -Xmx10g -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
      FHIR_DB_HOST: 10.5.6.2
      FHIR_DB_PORT: 5432
      FHIR_BASE: /medirad_hapifhir
      FHIR_DB_USER: medirad_hapifhir
    env_file: hapifhir.env
    logging:
      driver: json-file
      options:
        max-size: "10m"

  dns:
    container_name: dns
    image: andyshinn/dnsmasq:${DNS_TAG}
    volumes:
      - ./conf/dns/hosts:/etc/hosts
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.26.0.11

  irdbbui:
    container_name: irdbbui
    image: medirad-docker-virtual.artifact.b-com.com/irdbb-ui:${IRDBB_UI_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    
  stardog_db:
    container_name: stardog
    image: medirad-docker-virtual.artifact.b-com.com/stardog:${STARDOG_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    volumes:
      - stardog:/stardog
      - stardog-license:/stardog-license
      - /d4docker_archive:/stardog_db
    networks:
      default:
        aliases:
          - stardog
  
  semantic-translator:
    container_name: semantictranslator
    image: medirad-docker-virtual.artifact.b-com.com/semantic-translator:${SEMANTIC_TRANSLATOR_TAG}
    environment:
      PACS_HOST: pacsarc
      FHIR_HOST: fhir
      STARDOG_HOST: stardog
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - stardog_db
    networks:
      - default
      - irdbb_importer
    
  arc:
    image: osirixfoundation/irdbb-pacs:${KHEOPS_NGINX_ARC_TAG}
    container_name: pacsarc
    environment:
      - KHEOPS_TOKEN_FILE=/run/secrets/kheops_token
    networks:
      - default
      - kheops
    secrets:
      - kheops_token

  nginx:
    container_name: irdbbreverseproxy
    image: osirixfoundation/irdbb-reverse-proxy:${REVERSE_PROXY_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      MEDIRAD_NGINX_ENABLE_ELASTIC: "true"
      MEDIRAD_NGINX_LOGSTASH_URL: 10.5.7.4:5044
      MEDIRAD_NGINX_ELASTIC_INSTANCE: medirad
      IRDBB_ROOT_HOST: irdbb.kheops.online
    depends_on:
      - arc
      - semantic-translator
      - irdbbui
      - dns
      - fhir
    volumes:
      - ./conf/reverseproxy/openssl:/opt/local/etc/openssl
    secrets:
      - fullchain1.pem
      - privkey1.pem
      - client_secret

volumes:
  fhir-db-data:
  stardog:
  stardog-license:
  stardog-db:

secrets:
  fullchain1.pem:
    file: secrets/fullchain1.pem
  privkey1.pem:
    file: secrets/privkey1.pem
  client_secret:
    file: secrets/client_secret
  kheops_token:
    file: secrets/kheops_token

networks:
  default:
    external:
      name: medirad
  irdbb_importer:
    external:
      name: kheops_irdbb_importer_network
  kheops:
    external:
      name: kheops_reverseproxy_network
