version: "2.4"
services:
  sparklis:
    image: medirad-docker-virtual.artifact.b-com.com/sparklis:${SPARKLIS_TAG}
    container_name: sparklis

  fhirdb:
    image: postgres:10.4
    container_name: fhirdb
    environment:
      POSTGRES_DB: hapifhir
      POSTGRES_USER: medirad
      POSTGRES_PASSWORD: secret
    volumes:
      - fhir-db-data:/var/lib/postgresql/data

  fhir:
    container_name: fhir
    image: medirad-docker-virtual.artifact.b-com.com/hapi-fhir:${FHIR_TAG}
    environment:
      JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256m -Xmx6g #-XshowSettings:vm -version
      FHIR_DB_HOST: fhirdb
      FHIR_BASE: /hapifhir
      FHIR_DB_USER: medirad
      POSTGRES_DB: hapifhir
      POSTGRES_USER: medirad
    env_file: hapifhir.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - fhirdb
    mem_limit: 8g
    restart: always

  dns:
    container_name: dns
    image: andyshinn/dnsmasq:${DNS_TAG}
    volumes:
      - ./conf/dns/hosts:/etc/hosts
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.26.0.11

  irdbbui:
    container_name: irdbbui
    image: medirad-docker-virtual.artifact.b-com.com/irdbb-ui:${IRDBB_UI_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - arc
      - semantic-translator
      - fhir
    
  stardog_db:
    container_name: stardog
    image: medirad-docker-virtual.artifact.b-com.com/stardog:${STARDOG_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    volumes:
      - stardog:/stardog
      - stardog-license:/stardog-license
      - stardog-db:/stardog_db
    networks:
      default:
        aliases:
          - stardog
    mem_limit: 8g
  
  semantic-translator:
    container_name: semantictranslator
    image: medirad-docker-virtual.artifact.b-com.com/semantic-translator:${SEMANTIC_TRANSLATOR_TAG}
    environment:
      PACS_HOST: pacsarc
      FHIR_HOST: fhir
      STARDOG_HOST: stardog
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - stardog_db
    networks:
      - default
      - irdbb_importer
    mem_limit: 800m
    
  arc:
    image: osirixfoundation/irdbb-pacs:${KHEOPS_NGINX_ARC_TAG}
    container_name: pacsarc
    environment:
      - KHEOPS_TOKEN_FILE=/var/kheops_token
    volumes:
      - ./secrets/kheops_token:/var/kheops_token
    networks:
      - default
      - kheops

  nginx:
    container_name: irdbbreverseproxy
    image: osirixfoundation/irdbb-reverse-proxy:${REVERSE_PROXY_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      MEDIRAD_NGINX_ENABLE_ELASTIC: "true"
      MEDIRAD_NGINX_LOGSTASH_URL: 10.5.7.4:5044
      MEDIRAD_NGINX_ELASTIC_INSTANCE: medirad-staging
      IRDBB_ROOT_HOST: irdbb-staging.kheops.online
    depends_on:
      - arc
      - semantic-translator
      - irdbbui
      - dns
      - fhir
    volumes:
      - ./conf/reverseproxy/openssl:/opt/local/etc/openssl
      - ./secrets/fullchain1.pem:/run/secrets/fullchain1.pem
      - ./secrets/privkey1.pem:/run/secrets/privkey1.pem
      - ./secrets/client_secret:/run/secrets/client_secret

volumes:
  fhir-db-data:
  stardog:
  stardog-license:
  stardog-db:

networks:
  default:
    external:
      name: medirad
  irdbb_importer:
    external:
      name: kheops_irdbb_importer_network
  kheops:
    external:
      name: kheops_reverseproxy_network
