version: "3.1"
services:
  sparklis:
    image: medirad-docker-virtual.artifact.b-com.com/sparklis:${SPARKLIS_TAG}
    container_name: sparklis

  fhirdb:
    image: postgres:10.4
    container_name: fhirdb
    environment:
      POSTGRES_DB: hapifhir
      POSTGRES_USER: medirad
      POSTGRES_PASSWORD: secret
    volumes:
      - fhir-db-data:/var/lib/postgresql/data

  fhir:
    container_name: fhir
    image: medirad-docker-virtual.artifact.b-com.com/hapi-fhir:${FHIR_TAG}
    environment:
      JAVA_OPTIONS: -Xms10g -Xmx10g -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
      FHIR_DB_HOST: fhirdb
      FHIR_BASE: /hapifhir
      POSTGRES_DB: hapifhir
      POSTGRES_USER: medirad
      POSTGRES_PASSWORD: secret
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - fhirdb

  dns:
    container_name: dns
    image: andyshinn/dnsmasq:${DNS_TAG}
    volumes:
      - ./conf/dns/hosts:/etc/hosts
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.26.0.11

  irdbbui:
    container_name: irdbbui
    image: medirad-docker-virtual.artifact.b-com.com/irdbb-ui:${IRDBB_UI_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - arc
      - semantic-translator
      - fhir
    
  stardog_db:
    container_name: stardog
    image: medirad-docker-virtual.artifact.b-com.com/stardog:${STARDOG_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    volumes:
      - stardog:/stardog
      - stardog-license:/stardog-license
      - stardog-db:/stardog_db
    networks:
      default:
        aliases:
          - stardog
  
  semantic-translator:
    container_name: semantictranslator
    image: medirad-docker-virtual.artifact.b-com.com/semantic-translator:${SEMANTIC_TRANSLATOR_TAG}
    environment:
      PACS_HOST: pacsarc
      FHIR_HOST: fhir
      STARDOG_HOST: stardog
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - stardog_db
    
  arc:
    image: nginx:${KHEOPS_NGINX_ARC_TAG}
    container_name: pacsarc
    ports:
      - "8080:8080"
    volumes:
      - ./conf/nginxconf:/etc/nginx/
    extra_hosts:
      - "aneux.kheops.online:10.5.7.9"
    networks:
      - default
      - kheops

  nginx:
    container_name: irdbbreverseproxy
    image: nicolasvandooren/nginxmedirad:${REVERSE_PROXY_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      MEDIRAD_NGINX_ENABLE_ELASTIC: "true"
      MEDIRAD_NGINX_LOGSTASH_URL: 10.5.7.4:5044
      MEDIRAD_NGINX_ELASTIC_INSTANCE: medirad
    depends_on:
      - arc
      - semantic-translator
      - irdbbui
      - dns
      - fhir
    volumes:
      - ./conf/reverseproxy/conf:/usr/local/openresty/nginx/conf
      - ./conf/reverseproxy/openssl:/opt/local/etc/openssl
    secrets:
      - fullchain1.pem
      - privkey1.pem

volumes:
  fhir-db-data:
  stardog:
  stardog-license:
  stardog-db:

secrets:
  fullchain1.pem:
    file: secrets/fullchain1.pem
  privkey1.pem:
    file: secrets/privkey1.pem

networks:
  default:
    external:
      name: medirad
  kheops:
    external:
      name: kheops_reverseproxy_network
